// angular2-performstagram/src/posts/components/add-photo.component.ts
import {ChangeDetectionStrategy, Component, ViewChild} from '@angular/core';
import {FileUploader} from 'ng2-file-upload';
import {PostService} from '../services/post.service';
import {ModalService} from '../services/modal.service';
import {AuthService} from '../../auth/services/auth.service';
import {Observable} from 'rxjs/Observable';
import {UUID} from 'angular2-uuid';

@Component({changeDetection: ChangeDetectionStrategy.OnPush, selector: 'add-photo', template: `
     <div class="photo-grid__button_add">
                <button (click)="addPhotoModal.open()" class="like">+ Add image</button>
                  <modal #addPhotoModal [hideCloseButton]="true" [closeOnOutsideClick]="true">
        <modal-content>
        <h2>Upload a image</h2>
        <label for="uploader-input" ng2FileDrop (fileOver)="fileOverBase($event)" [uploader]="uploader">
            <div class="add-photo-drop-zone">Try dropping some files here, or click to select files to upload.
                <div *ngFor="let item of uploader.queue" class="media">
                    <img src="" imgPreview [image]="item?._file" class="media-object" />
                </div>  
            </div>
        </label>
        <input type="file" ng2FileSelect [uploader]="uploader"  id="uploader-input" style="display:none" accept="image/*" (click)="onClick($event);" (change)="onChange($event)" />
            <form
                ref="uploadForm"
                class="comment-form">
                <input type="text" #caption placeholder="caption"/>
                <div class="modal-grid__button">
                    <button class="modal-grid__button_submit" (click)="handleCreatePost(caption.value)">
                        <input type="submit" value="Upload"/></button>
                </div>
        </form>
        </modal-content>
    </modal>
     </div>
  `})

export class AddPhotoComponent {
    @ViewChild('addPhotoModal')modal;

    public hasBaseDropZoneOver : boolean = false;
    public uploader : FileUploader = new FileUploader({
        isHTML5: true,
        allowedMimeType: [
            'image/png', 'image/jpg', 'image/jpeg', 'image/gif'
        ],
        queueLimit: 1
    });
    constructor(public postService : PostService, private modalService : ModalService, private authService : AuthService) {}
    onChange(event : any) : void {}
    fileOverBase(e : any) : void {
        this.hasBaseDropZoneOver = e;
    }
    handleCreatePost(postCaption : string) {

        if (this.uploader.queue.length > 0) {
            let file : File = this.uploader.queue[0]._file;
            this
                .modal
                .close();
            let caption : string = postCaption;
            let author : string = 'test';
            let id : string = UUID.UUID();
            this
                .modalService
                .closeModal(false);
            this
                .authService
                .getUserName()
                .subscribe(v => {
                    author = v;
                });

            const newPost = {
                author,
                caption,
                file,
                id
            }

            this
                .postService
                .createPost(newPost);

        } else {
            this
                .modal
                .close();
        }

    }
    onClick() {

        this.uploader.queue
        this
            .uploader
            .clearQueue();
        // this     .modal     .open(AddPhotoModalComponent, new
        // AdditionCalculateWindowData(3, 4));

    }
}

// react-performstagram/client/posts/components/AddPhoto.js
import React, {Component} from 'react';
import Modal from 'react-modal';
var Dropzone = require('react-dropzone');
const uuidV4 = require('uuid/v4');
import {firebaseAuth} from '../../firebase'
const appElement = document.getElementById('root');
const customStyles = {
    content: {
        top: '50%',
        left: '50%',
        right: 'auto',
        bottom: 'auto',
        marginRight: '-50%',
        transform: 'translate(-50%, -50%)'
    }
};

class AddPhoto extends Component {

    handleSubmit(e) {

        e.preventDefault();

        const file = this.props.modal.acceptedFile;
        this
            .props
            .actions
            .modalActions
            .closeModal();
        const author = this.props.auth.displayName;
        const caption = this.refs.caption.value;
        const id = uuidV4()

        const newPost = {
            author,
            caption,
            id,
            file
        }

        this
            .props
            .actions
            .postActions
            .createPost(newPost)
        // reset form
        this
            .refs
            .uploadForm
            .reset();

    }
    render() {

        return (
            <div className="photo-grid__button_add">
                <button onClick={this.props.actions.modalActions.openModal} className="like">+ Add image</button>
                <Modal
                    isOpen={this.props.modal.modalIsOpen}
                    onRequestClose={this.props.actions.modalActions.closeModal}
                    style={customStyles}
                    contentLabel="Upload Image Modal">
                    <h2 ref="subtitle">Upload a image</h2>
                    <Dropzone
                        onDrop={this.props.actions.postActions.onDrop}
                        multiple={false}
                        accept={'image/*'}>
                        <div>Try dropping some files here, or click to select files to upload.</div>
                        {this.props.modal.acceptedFile
                            ? <img src={this.props.modal.acceptedFile.preview}/>
                            : null}
                    </Dropzone>
                    <form
                        ref='uploadForm'
                        className='comment-form'
                        onSubmit={this
                        .handleSubmit
                        .bind(this)}>
                        <input type='text' className='caption' ref='caption' placeholder='caption'/>
                        <div className="modal-grid__button">
                            <button className="modal-grid__button_submit">
                                <input type='submit' value="Upload"/></button>
                        </div>
                    </form>

                </Modal>
            </div>
        );
    }
}

export default AddPhoto;
