// react-performstagram/client/components/Comments.js
import React, {Component} from 'react';

class Comments extends Component {
    renderComment(comment, i) {
        return (
            <div className='comment' key={i}>
                <p>
                    <strong>{comment.user}</strong>
                    {comment.text}
                    <button
                        className='remove-comment'
                        onClick={this
                        .props
                        .removeComment
                        .bind(null, this.props.params.postId, i)}>&times;</button>
                </p>
            </div>
        )
    }
    handleSubmit(e) {
        e.preventDefault();
        const {postId} = this.props.params;
        const author = this.refs.author.value;
        const comment = this.refs.comment.value;
        this
            .props
            .addComment(postId, author, comment);
        this
            .refs
            .commentForm
            .reset();

    }
    render() {
        return (
            <div className='comments'>
                {this
                    .props
                    .postComments
                    .map(this.renderComment.bind(this))}
                <form
                    ref='commentForm'
                    className='comment-form'
                    onSubmit={this
                    .handleSubmit
                    .bind(this)}>
                    <input type='text' ref='author' value={this.props.auth.id}/>
                    <input type='text' ref='comment' placeholder='comment'/>
                    <input type='submit' hidden/>

                </form>
            </div>
        );
    }
}

export default Comments;

// angular2-performstagram/src/posts/components/comments.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Output,
  Input,
  ViewChild
} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import {AuthService} from '../../auth/services/auth.service';
import {CommentService} from '../services/comment.service';
import Comment from '../datatypes/comment';

@Component({changeDetection: ChangeDetectionStrategy.OnPush, selector: 'comments', template: `
<div class="comments">
    <div *ngFor="let commentObservableArray of commentsForSelectedPost | async">
        <div *ngFor="let comment of commentObservableArray">
            <comment *ngIf="comment?.author && comment?.comment" [author]="comment.author" [text]="comment.comment" [key]="comment.key"
                [postId]="postId">
                </comment>
        </div>
    </div>
    <form class="comment-form" (ngSubmit)="onSubmit(author.value, comment.value); comment.value= ''">
        <input type="text" #author [value]="authService.getUserName() | async" readOnly/>
        <input type="text" #comment placeholder="comment" />
        <button type="submit" hidden>Submit</button>
    </form>
</div>
`})

export class CommentsComponent {
  @Input()commentsForSelectedPost : Observable < any >;
  @Input()postId : string;
  @ViewChild('comment')comment;

  constructor(private authService : AuthService, private commentService : CommentService) {}

  onSubmit(author : string, comment : string) {
    this
      .commentService
      .createCommment(new Comment(author, comment), this.postId)
  }
}
<div *ngIf="commentsForSelectedPost" class="comments">
    <div *ngFor="let commentObservableArray of commentsForSelectedPost | async">
        <div *ngIf="commentObservableArray">
            <div *ngFor="let comment of commentObservableArray">
                <comment *ngIf="comment?.author && comment?.comment" [author]="comment?.author" [text]="comment?.comment"></comment>
            </div>
        </div>
    </div>
    <form class="comment-form" (ngSubmit)="onSubmit(author.value, comment.value)">
        <input type="text" #author [value]="authService.getUserName() | async" readOnly/>
        <input type="text" #comment placeholder="comment" />
        <input type="submit " hidden/>
    </form>
</div>
