// react-performstagram/client/posts/components/Photo.js
import React, {Component} from 'react';
import {Link} from 'react-router';
class Photo extends Component {

    render() {
        const {post, i, comments} = this.props;

        return (
            <figure className='grid-figure'>
                {post !== undefined && comments !== undefined
                    ? (
                        <div className="grid-photo-wrap">
                            <Link to={`/single/${post.code}`}>
                                <img src={post.display_src} alt={post.caption} className='grid-photo'/>
                            </Link>

                            <figcaption>
                                <p>{post.caption}</p>
                                <div className="control-buttons">
                                    <button
                                        onClick={() => {
                                        this
                                            .props
                                            .actions
                                            .postActions
                                            .updatePost(i, post)
                                    }}
                                        className="like">&hearts; {post.likes}</button>
                                    <Link className='button' to={`/single/${post.code}`}>
                                        <span className="comment-count">

                                            <span className="speech-bubble"></span>
                                            &nbsp; {this
                                                .props
                                                .comments
                                                .map((commentsObject) => {

                                                    if (commentsObject.code === post.code) {
                                                        return ((Object.keys(commentsObject).length) - 1)
                                                    }

                                                })
}
                                        </span>

                                    </Link>
                                </div>
                            </figcaption>
                        </div>
                    )
                    : null}

            </figure>
        );
    }
}

export default Photo;

// angular2-performstagram/src/posts/components/photo.component.ts
import {ChangeDetectionStrategy, Component, EventEmitter, Output, Input} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import {Router} from '@angular/router'
import Posts from '../posts';
import Comments from '../comments';
@Component({changeDetection: ChangeDetectionStrategy.OnPush, selector: 'photo', template: require('./photo.component.html')})

export class PhotoComponent {
    @Input()posts : Observable < Posts >;
    @Input()comments : Observable < Comments >;

    @Output()updatePost : EventEmitter < any > = new EventEmitter(false);

    constructor(public router : Router) {
        console.log(this.posts);
        console.log(this.comments);
    }
    countComments(comments) : number {
        // -1 because also they key for the right comment is saved in the object.
        return Object
            .keys(comments)
            .length - 1
    }

    onSelect(photoId : string) {
        this
            .router
            .navigate(['/single', photoId])
    }

}

<figure *ngFor="let post of posts | async" class="grid-figure">
    <div class="grid-photo-wrap">
        <img [src]="post.display_src" [alt]="post.caption" class="grid-photo" (click)="onSelect(post.code)" />
        <figcaption>
            <p>{{post.caption}}</p>
            <div class="control-buttons">
                <button onClick={postService.updatePost(post)} class="like">&hearts; {{post.likes}}</button>
                <button>
                        <span class="comment-count">
                            <span class="speech-bubble"></span><span *ngFor="let comment of comments | async"><span *ngIf="comment.code === post.code">  &nbsp; {{countComments(comment)}} </span></span>
                        </span>
                    </button>
            </div>
        </figcaption>
    </div>
</figure>
