// react-performstagram/client/components/Photo.js
import React, {Component} from 'react';
import {Link} from 'react-router';
class Photo extends Component {

    render() {
        const {post, i, comments} = this.props;

        return (
            <figure className='grid-figure'>
                {post !== undefined && comments !== undefined
                    ? (
                        <div className="grid-photo-wrap">
                            <Link to={`/view/${post.code}`}>
                                <img src={post.display_src} alt={post.caption} className='grid-photo'/>
                            </Link>

                            <figcaption>
                                <p>{post.caption}</p>
                                <div className="control-buttons">
                                    <button
                                        onClick={() => {
                                        this
                                            .props
                                            .updatePost(i, post)
                                    }}
                                        className="like">&hearts; {post.likes}</button>
                                    <Link className='button' to={`/view/${post.code}`}>
                                        <span className="comment-count">

                                            <span className="speech-bubble"></span>
                                            &nbsp; {this
                                                .props
                                                .comments
                                                .map((commentsObject) => {

                                                    if (commentsObject.code === post.code) {
                                                        return ((Object.keys(commentsObject).length) - 1)
                                                    }

                                                })
}
                                        </span>

                                    </Link>
                                </div>
                            </figcaption>
                        </div>
                    )
                    : null}

            </figure>
        );
    }
}

export default Photo;

// angular2-performstagram/src/posts/components/photo.component.ts
import {ChangeDetectionStrategy, Component, EventEmitter, Output, Input} from '@angular/core';
import {Observable} from 'rxjs/Observable';
import Posts from '../posts';

@Component({changeDetection: ChangeDetectionStrategy.OnPush, selector: 'photo', template: require('./photo.component.html')})

export class PhotoComponent {
    @Input()posts : Observable < Posts[] >;

    @Output()updatePost : EventEmitter < any > = new EventEmitter(false);

}

<div *ngFor="let post of posts | async ">
    <figure class='grid-figure'>
        <div class="grid-photo-wrap">
            <img src={{post.display_src}} alt={{post.caption}} class='grid-photo' />
            <figcaption>
                <p>{{post.caption}}</p>
                <div class="control-buttons">
                    <button onClick={} class="like">&hearts; {{post.likes}}</button>
                    <button>
                        <span class="comment-count">
                            <span class="speech-bubble"></span> &nbsp; 1
                        </span>
                    </button>
                </div>
            </figcaption>
        </div>
    </figure>
</div>
